// Mapping frontend pour les descriptions d'activité
export const ActivityTypeDescriptions: Record<string, string> = {
  SIGN_UP: 'Inscription',
  SIGN_IN: 'Connexion',
  SIGN_OUT: 'Déconnexion',
  UPDATE_PASSWORD: 'Changement de mot de passe',
  DELETE_ACCOUNT: 'Suppression du compte',
  UPDATE_ACCOUNT: 'Mise à jour du compte',
  TEST: "Test d'activité",
  ASSIGN_ROLE: "Attribution d'un rôle",
  CHECK_PERMISSION: 'Vérification de permission',
  GET_CUSTOM_ROLES: 'Récupération des rôles personnalisés',
  CREATE_ROLE: "Création d'un rôle",
  CREATE_PERMISSION: "Création d'une permission",
  UPDATE_ROLE: "Mise à jour d'un rôle",
  GET_SUBSCRIPTION_BY_USER: "Consultation de l'abonnement utilisateur",
  START_TRIAL: "Démarrage d'une période d'essai",
  CANCEL_TRIAL: "Annulation de l'essai",
  SUBSCRIBING: 'Souscription en cours',
  GET_SUBSCRIBE_STATUS: "Vérification du statut d'abonnement",
  SUBSCRIPTION_CREATED: 'Abonnement créé',
  SUBSCRIPTION_UPDATED: 'Abonnement mis à jour',
  SUBSCRIPTION_CANCELLED: 'Abonnement annulé',
  SUBSCRIPTION_DELETED: 'Abonnement supprimé',
  PAYMENT_SUCCEEDED: 'Paiement réussi',
  PAYMENT_FAILED: 'Échec du paiement',
  SUBSCRIPTION_ERROR: "Erreur d'abonnement",
  PAYMENT_RETRY: 'Nouvelle tentative de paiement',
  SUBSCRIPTION_EXPIRED: 'Abonnement expiré',
  TRIAL_ENDING_NOTIFICATION: "Notification de fin d'essai",
  CALL_WEBHOOK: "Appel d'un webhook",
  CANCEL_SUBSCRIPTION: "Annulation de l'abonnement",
  CHANGE_SUBSCRIPTION_PLAN: "Changement de plan d'abonnement"
}
