export enum ActivityType {
  SIGN_UP = 'SIGN_UP',
  SIGN_IN = 'SIGN_IN',
  SIGN_OUT = 'SIGN_OUT',
  UPDATE_PASSWORD = 'UPDATE_PASSWORD',
  DELETE_ACCOUNT = 'DELETE_ACCOUNT',
  UPDATE_ACCOUNT = 'UPDATE_ACCOUNT',
  TEST = 'TEST',
  ASSIGN_ROLE = 'ASSIGN_ROLE',
  CHECK_PERMISSION = 'CHECK_PERMISSION',
  GET_CUSTOM_ROLES = 'GET_CUSTOM_ROLES',
  CREATE_ROLE = 'CREATE_ROLE',
  CREATE_PERMISSION = 'CREATE_PERMISSION',
  UPDATE_ROLE = 'UPDATE_ROLE',
  GET_SUBSCRIPTION_BY_USER = 'GET_SUBSCRIPTION_BY_USER',
  START_TRIAL = 'START_TRIAL',
  CANCEL_TRIAL = 'CANCEL_TRIAL',
  SUBSCRIBING = 'SUBSCRIBING',
  GET_SUBSCRIBE_STATUS = 'GET_SUBSCRIBE_STATUS',
  SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_UPDATED = 'SUBSCRIPTION_UPDATED',
  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_DELETED = 'SUBSCRIPTION_DELETED',
  PAYMENT_SUCCEEDED = 'PAYMENT_SUCCEEDED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  SUBSCRIPTION_ERROR = 'SUBSCRIPTION_ERROR',
  PAYMENT_RETRY = 'PAYMENT_RETRY',
  SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED',
  TRIAL_ENDING_NOTIFICATION = 'TRIAL_ENDING_NOTIFICATION',
  CALL_WEBHOOK = 'CALL_WEBHOOK',
  CANCEL_SUBSCRIPTION = 'CANCEL_SUBSCRIPTION',
  CHANGE_SUBSCRIPTION_PLAN = 'CHANGE_SUBSCRIPTION_PLAN'
}

export const ActivityTypeDescriptions: Record<ActivityType, string> = {
  [ActivityType.SIGN_UP]: 'Inscription',
  [ActivityType.SIGN_IN]: 'Connexion',
  [ActivityType.SIGN_OUT]: 'Déconnexion',
  [ActivityType.UPDATE_PASSWORD]: 'Changement de mot de passe',
  [ActivityType.DELETE_ACCOUNT]: 'Suppression du compte',
  [ActivityType.UPDATE_ACCOUNT]: 'Mise à jour du compte',
  [ActivityType.TEST]: "Test d'activité",
  [ActivityType.ASSIGN_ROLE]: "Attribution d'un rôle",
  [ActivityType.CHECK_PERMISSION]: 'Vérification de permission',
  [ActivityType.GET_CUSTOM_ROLES]: 'Récupération des rôles personnalisés',
  [ActivityType.CREATE_ROLE]: "Création d'un rôle",
  [ActivityType.CREATE_PERMISSION]: "Création d'une permission",
  [ActivityType.UPDATE_ROLE]: "Mise à jour d'un rôle",
  [ActivityType.GET_SUBSCRIPTION_BY_USER]: "Consultation de l'abonnement utilisateur",
  [ActivityType.START_TRIAL]: "Démarrage d'une période d'essai",
  [ActivityType.CANCEL_TRIAL]: "Annulation de l'essai",
  [ActivityType.SUBSCRIBING]: 'Souscription en cours',
  [ActivityType.GET_SUBSCRIBE_STATUS]: "Vérification du statut d'abonnement",
  [ActivityType.SUBSCRIPTION_CREATED]: 'Abonnement créé',
  [ActivityType.SUBSCRIPTION_UPDATED]: 'Abonnement mis à jour',
  [ActivityType.SUBSCRIPTION_CANCELLED]: 'Abonnement annulé',
  [ActivityType.SUBSCRIPTION_DELETED]: 'Abonnement supprimé',
  [ActivityType.PAYMENT_SUCCEEDED]: 'Paiement réussi',
  [ActivityType.PAYMENT_FAILED]: 'Échec du paiement',
  [ActivityType.SUBSCRIPTION_ERROR]: "Erreur d'abonnement",
  [ActivityType.PAYMENT_RETRY]: 'Nouvelle tentative de paiement',
  [ActivityType.SUBSCRIPTION_EXPIRED]: 'Abonnement expiré',
  [ActivityType.TRIAL_ENDING_NOTIFICATION]: "Notification de fin d'essai",
  [ActivityType.CALL_WEBHOOK]: "Appel d'un webhook",
  [ActivityType.CANCEL_SUBSCRIPTION]: "Annulation de l'abonnement",
  [ActivityType.CHANGE_SUBSCRIPTION_PLAN]: "Changement de plan d'abonnement"
}
