export enum ActivityType {
  SIGN_UP = 'SIGN_UP',
  SIGN_IN = 'SIGN_IN',
  SIGN_OUT = 'SIGN_OUT',
  UPDATE_PASSWORD = 'UPDATE_PASSWORD',
  DELETE_ACCOUNT = 'DELETE_ACCOUNT',
  UPDATE_ACCOUNT = 'UPDATE_ACCOUNT',
  TEST = 'TEST',
  ASSIGN_ROLE = 'ASSIGN_ROLE',
  CHECK_PERMISSION = 'CHECK_PERMISSION',
  GET_CUSTOM_ROLES = 'GET_CUSTOM_ROLES',
  CREATE_ROLE = 'CREATE_ROLE',
  CREATE_PERMISSION = 'CREATE_PERMISSION',
  UPDATE_ROLE = 'UPDATE_ROLE',
  GET_SUBSCRIPTION_BY_USER = 'GET_SUBSCRIPTION_BY_USER',
  START_TRIAL = 'START_TRIAL',
  CANCEL_TRIAL = 'CANCEL_TRIAL',
  SUBSCRIBING = 'SUBSCRIBING',
  GET_SUBSCRIBE_STATUS = 'GET_SUBSCRIBE_STATUS',
  SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_UPDATED = 'SUBSCRIPTION_UPDATED',
  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_DELETED = 'SUBSCRIPTION_DELETED',
  PAYMENT_SUCCEEDED = 'PAYMENT_SUCCEEDED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  SUBSCRIPTION_ERROR = 'SUBSCRIPTION_ERROR',
  PAYMENT_RETRY = 'PAYMENT_RETRY',
  SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED',
  TRIAL_ENDING_NOTIFICATION = 'TRIAL_ENDING_NOTIFICATION',
  CALL_WEBHOOK = 'CALL_WEBHOOK',
  CANCEL_SUBSCRIPTION = 'CANCEL_SUBSCRIPTION',
  CHANGE_SUBSCRIPTION_PLAN = 'CHANGE_SUBSCRIPTION_PLAN',
  AUTO_SAVE_POST = 'AUTO_SAVE_POST',
  CREATE_POST = 'CREATE_POST',
  PREVIEW_POST = 'PREVIEW_POST',
  UPDATE_POST = 'UPDATE_POST',
  DELETE_POST = 'DELETE_POST',
  CREATE_COMMENT = 'CREATE_COMMENT',
  UPDATE_COMMENT = 'UPDATE_COMMENT',
  DELETE_COMMENT = 'DELETE_COMMENT',
  LIKE_POST = 'LIKE_POST',
  UNLIKE_POST = 'UNLIKE_POST',
  LIKE_COMMENT = 'LIKE_COMMENT',
  UNLIKE_COMMENT = 'UNLIKE_COMMENT',
  SHARE_POST = 'SHARE_POST',
  UPLOAD_MEDIA = 'UPLOAD_MEDIA',
  DELETE_MEDIA = 'DELETE_MEDIA',
  TAG_POST = 'TAG_POST',
  UNTAG_POST = 'UNTAG_POST',
  CREATE_TAG = 'CREATE_TAG',
  UPDATE_TAG = 'UPDATE_TAG',
  DELETE_TAG = 'DELETE_TAG',
  CREATE_CATEGORY = 'CREATE_CATEGORY',
  UPDATE_CATEGORY = 'UPDATE_CATEGORY',
  DELETE_CATEGORY = 'DELETE_CATEGORY',
  CREATE_POST_MEDIA = 'CREATE_POST_MEDIA',
  DELETE_POST_MEDIA = 'DELETE_POST_MEDIA',
  CREATE_POST_TAG = 'CREATE_POST_TAG',
  DELETE_POST_TAG = 'DELETE_POST_TAG',
  CREATE_USER_ROLE = 'CREATE_USER_ROLE',
  UPDATE_USER_ROLE = 'UPDATE_USER_ROLE',
  DELETE_USER_ROLE = 'DELETE_USER_ROLE'
}

export const ActivityTypeDescriptions: Record<ActivityType, string> = {
  [ActivityType.PREVIEW_POST]: 'Prévisualisation markdown',
  [ActivityType.SIGN_UP]: 'Inscription',
  [ActivityType.SIGN_IN]: 'Connexion',
  [ActivityType.SIGN_OUT]: 'Déconnexion',
  [ActivityType.UPDATE_PASSWORD]: 'Changement de mot de passe',
  [ActivityType.DELETE_ACCOUNT]: 'Suppression du compte',
  [ActivityType.UPDATE_ACCOUNT]: 'Mise à jour du compte',
  [ActivityType.TEST]: "Test d'activité",
  [ActivityType.ASSIGN_ROLE]: "Attribution d'un rôle",
  [ActivityType.CHECK_PERMISSION]: 'Vérification de permission',
  [ActivityType.GET_CUSTOM_ROLES]: 'Récupération des rôles personnalisés',
  [ActivityType.CREATE_ROLE]: "Création d'un rôle",
  [ActivityType.CREATE_PERMISSION]: "Création d'une permission",
  [ActivityType.UPDATE_ROLE]: "Mise à jour d'un rôle",
  [ActivityType.GET_SUBSCRIPTION_BY_USER]: "Consultation de l'abonnement utilisateur",
  [ActivityType.START_TRIAL]: "Démarrage d'une période d'essai",
  [ActivityType.CANCEL_TRIAL]: "Annulation de l'essai",
  [ActivityType.SUBSCRIBING]: 'Souscription en cours',
  [ActivityType.GET_SUBSCRIBE_STATUS]: "Vérification du statut d'abonnement",
  [ActivityType.SUBSCRIPTION_CREATED]: 'Abonnement créé',
  [ActivityType.SUBSCRIPTION_UPDATED]: 'Abonnement mis à jour',
  [ActivityType.SUBSCRIPTION_CANCELLED]: 'Abonnement annulé',
  [ActivityType.SUBSCRIPTION_DELETED]: 'Abonnement supprimé',
  [ActivityType.PAYMENT_SUCCEEDED]: 'Paiement réussi',
  [ActivityType.PAYMENT_FAILED]: 'Échec du paiement',
  [ActivityType.SUBSCRIPTION_ERROR]: "Erreur d'abonnement",
  [ActivityType.PAYMENT_RETRY]: 'Nouvelle tentative de paiement',
  [ActivityType.SUBSCRIPTION_EXPIRED]: 'Abonnement expiré',
  [ActivityType.TRIAL_ENDING_NOTIFICATION]: "Notification de fin d'essai",
  [ActivityType.CALL_WEBHOOK]: "Appel d'un webhook",
  [ActivityType.CANCEL_SUBSCRIPTION]: "Annulation de l'abonnement",
  [ActivityType.CHANGE_SUBSCRIPTION_PLAN]: "Changement de plan d'abonnement",
  [ActivityType.AUTO_SAVE_POST]: 'Sauvegarde automatique de l’article',
  [ActivityType.CREATE_POST]: 'Création d’un article',
  [ActivityType.UPDATE_POST]: 'Mise à jour d’un article',
  [ActivityType.DELETE_POST]: 'Suppression d’un article',
  [ActivityType.CREATE_COMMENT]: 'Création d’un commentaire',
  [ActivityType.UPDATE_COMMENT]: 'Mise à jour d’un commentaire',
  [ActivityType.DELETE_COMMENT]: 'Suppression d’un commentaire',
  [ActivityType.LIKE_POST]: 'Aimer un article',
  [ActivityType.UNLIKE_POST]: 'Ne plus aimer un article',
  [ActivityType.LIKE_COMMENT]: 'Aimer un commentaire',
  [ActivityType.UNLIKE_COMMENT]: 'Ne plus aimer un commentaire',
  [ActivityType.SHARE_POST]: 'Partager un article',
  [ActivityType.UPLOAD_MEDIA]: 'Téléversement de média',
  [ActivityType.DELETE_MEDIA]: 'Suppression de média',
  [ActivityType.TAG_POST]: 'Taguer un article',
  [ActivityType.UNTAG_POST]: 'Détaguer un article',
  [ActivityType.CREATE_TAG]: 'Création d’un tag',
  [ActivityType.UPDATE_TAG]: 'Mise à jour d’un tag',
  [ActivityType.DELETE_TAG]: 'Suppression d’un tag',
  [ActivityType.CREATE_CATEGORY]: 'Création d’une catégorie',
  [ActivityType.UPDATE_CATEGORY]: 'Mise à jour d’une catégorie',
  [ActivityType.DELETE_CATEGORY]: 'Suppression d’une catégorie',
  [ActivityType.CREATE_POST_MEDIA]: 'Ajout de média à un article',
  [ActivityType.DELETE_POST_MEDIA]: 'Suppression de média d’un article',
  [ActivityType.CREATE_POST_TAG]: 'Ajout de tag à un article',
  [ActivityType.DELETE_POST_TAG]: 'Suppression de tag d’un article',
  [ActivityType.CREATE_USER_ROLE]: 'Création d’un rôle utilisateur',
  [ActivityType.UPDATE_USER_ROLE]: 'Mise à jour d’un rôle utilisateur',
  [ActivityType.DELETE_USER_ROLE]: 'Suppression d’un rôle utilisateur',
}
